In [1]:
import src.w_and_doppler_generator as w_and_doppler_generator
import src.features_and_labels_generator as features_and_labels_generator
import src.Config as config
import src.debug_utils as debug_utils
from src.detecting_region_info_generator import generate_detecting_region_infos
from matplotlib.patches import Polygon
import matplotlib.pyplot as plt

# 生成500组四点配置
# detecting_region_infos = generate_detecting_region_infos(config.detecting_region_nums)

# print("The first configuration:")
# detecting_region_infos[0].draw_figure()


In [2]:
import src.doppler_info as doppler_info

doppler_info = doppler_info.DopplerInfo(config.c, config.fc, config.time_interval)


In [3]:
import src.trajectory_generator as trajectory_generator
from src.w_and_doppler_generator import extract_coords_from_lines
import src.get_phi_info as get_phi_info
import numpy as np

def get_features_and_labels(detecting_region_nums,lines_to_generate_per_region,seed):
    detecting_region_infos = generate_detecting_region_infos(detecting_region_nums)

# training features and labels
    features_stage1 = [] #长度为detecting_region_num_len 
    phis_labels_stage1 = [] #长度为detecting_region_num_len
    for detecting_region_info in detecting_region_infos:
        '''
        第一阶段：输入 （w12,fd12,(T,RX1)）,（w13,fd13,(T,RX3)）,(w14,fd14,(T,RX4))

        '''

        [lines_a, lines_b] = trajectory_generator.generate_lines(
            detecting_region_info=detecting_region_info,
            time_interval=config.time_interval,
            num_lines=lines_to_generate_per_region,
            seed=seed
        )

        coords_a = extract_coords_from_lines(lines_a)
        coords_b = extract_coords_from_lines(lines_b)
        data_length = np.shape(coords_a)[0]
        phis_1234 = []


        for i in range(data_length):
            coord_a = coords_a[i]
            coord_b = coords_b[i]
            [phi1, phi2, phi3, phi4] = get_phi_info.get_angle_phi(
                detecting_region_info, coord_a, coord_b
            )
            phis_1234.append([phi1, phi2, phi3, phi4])



        [w, doppler] = w_and_doppler_generator.generateWAndDoppler(
            detecting_region_info=detecting_region_info,
            doppler_info=doppler_info,
            coords_a=coords_a,
            coords_b=coords_b,
            phis_1234=phis_1234,
        )

        assert(len(lines_a) == len(lines_b))

        [feature_stage1,phis_label_stage1] = features_and_labels_generator.generateFeaturesAndLabelsStage1(
            phis1234=phis_1234,
            w=w,
            doppler=doppler,
            detecting_region_info=detecting_region_info
        )
        features_stage1.append(feature_stage1)
        phis_labels_stage1.append(phis_label_stage1)
    features_stage1 = np.concatenate(features_stage1,axis=0)
    phis_labels_stage1 = np.concatenate(phis_labels_stage1, axis=0)
    # debug_utils.print_lines_shape(lines_a)
    # debug_utils.visualizeLines(detecting_region_info, lines=lines_a, color='blue')
    # debug_utils.visualizeLines(detecting_region_info, lines=lines_b, color='red')
    return (feature_stage1,phis_labels_stage1)
    


In [4]:
(train_features_stage1,train_phis_labels_stage1) = get_features_and_labels(config.train_detecting_region_nums,config.train_num_of_lines_to_generate_per_region,seed=42)
(test_features_stage1,test_phis_labels_stage1) = get_features_and_labels(config.test_detecting_region_nums,config.test_num_of_lines_to_generate_per_region,seed=66)
print(train_features_stage1)
print(train_phis_labels_stage1)
print(test_features_stage1)
print(test_phis_labels_stage1)

[[ 1.15565385e+02  7.65832911e-01  1.30516689e+02  1.71294712e+00
   1.35807534e+02  2.59840564e+00  8.06436080e+01  3.77207126e+02
   8.75495797e+00  1.08790069e+02  9.26837940e+01 -1.09391075e+01]
 [ 1.15565385e+02  7.65832911e-01  1.30516689e+02  1.71294712e+00
   1.35807534e+02  2.59840564e+00  9.82180932e+02  3.41585028e+02
  -1.78086352e+04  4.66003879e+02  1.09399176e+02 -7.60335687e+01]]
[[ 0.22100649  0.37800577 -0.81073856 -0.92335164]
 [ 0.75142049  0.81893308 -0.31342745 -0.92309512]
 [ 0.91351165 -0.22592334 -0.32772019 -0.98265034]
 [ 0.71827519  0.8598977  -0.34778297 -0.97577115]]
[[ 1.19427905e+02  4.59903553e-01  1.22434681e+02  1.42797718e+00
   1.11877207e+02  2.34521017e+00  1.04054648e+02  3.25353082e+02
   6.43380210e+03  1.36065429e+02 -4.43082292e+01 -5.50999941e+01]
 [ 1.19427905e+02  4.59903553e-01  1.22434681e+02  1.42797718e+00
   1.11877207e+02  2.34521017e+00  1.79520390e+01 -3.20238776e+02
  -3.41107618e+04 -5.36590806e+02 -5.24208021e+02 -6.94924577e+01

In [5]:
import os
import time

current_time = time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime())
result_folder = "results/" + current_time
os.makedirs(result_folder)

training_results_folder = result_folder + "/training"
os.makedirs(training_results_folder)

testing_results_folder_csv = result_folder + "/testing_long_1"
os.makedirs(testing_results_folder_csv)

testing_results_folder_plt = result_folder + "/testing_long_2"
os.makedirs(testing_results_folder_plt)

# testing_results_folder_short = result_folder + "/testing_short_1"
# os.makedirs(testing_results_folder_short)


In [6]:
import numpy as np
import csv

# the label is [the distance to detecting_region_info.transimssion_position from the point, the angle between x axis and the line from the point to detecting_region_info.transimssion_position], i want to convert to the coordinates of the point


def labels_to_coords(detecting_region_info, labels):
    ref = detecting_region_info.transmittor_position

    coords = []

    for label in labels:
        distance = label[0]
        angle = label[1]

        x = ref[0] + distance * np.cos(angle)
        y = ref[1] + distance * np.sin(angle)

        coords.append([x, y])

    return np.array(coords)


def plot_result(detecting_region_info, loss_to_show, trues, predicteds, folder_name, plot_name):
    plt.figure(figsize=(10, 6))
    plt.scatter(
        trues[:, 0],
        trues[:, 1],
        label="True",
        marker="o",
        s=30,
        alpha=0.7,
    )
    plt.scatter(
        predicteds[:, 0],
        predicteds[:, 1],
        label="Predicted",
        marker="x",
        s=30,
        alpha=0.7,
    )
    plt.xlabel("X-coordinate")
    plt.ylabel("Y-coordinate")
    plt.legend()
    plt.title("True vs. Predicted")
    plt.grid(True)
    
    plt.gca().add_patch(Polygon([detecting_region_info.v1, detecting_region_info.v2, detecting_region_info.v4, detecting_region_info.v3], fill=False))

    plt.text(
        0,
        0,
        f"Loss: {loss_to_show}",
        ha="left",
        va="bottom",
        transform=plt.gca().transAxes,
    )
    test_result_name = folder_name + '/' + plot_name
    plt.savefig(test_result_name)

    plt.show()


def save_results_as_csv(true_labels, predicted_labels, output_file):
    """
    Save the true and predicted labels to a CSV file.
    
    Args:
    - true_labels: numpy array of true labels.
    - predicted_labels: numpy array of predicted labels.
    - output_file: str, path to the output CSV file.
    """
    
    with open(output_file, mode='w', newline='') as file:
        writer = csv.writer(file)
        
        # Write the header
        writer.writerow(['true', 'predicted'])
        
        # Write the true and predicted values
        for true, predicted in zip(true_labels, predicted_labels):
            writer.writerow([list(true), list(predicted)])

In [7]:

# dataset = {}
# dataset['train_input'] = torch.tensor(train_features).float().to(device)
# dataset['test_input'] = torch.tensor(test_short_features).float().to(device)
# dataset['train_label'] = torch.tensor(train_coor_labels).float().to(device)
# dataset['test_short_label'] = torch.tensor(test_short_coor_labels).float().to(device)
# dataset['test_long_label'] = torch.tensor(test_long_coor_labels).float().to(device)

# dataset['train_input'].shape,dataset['train_label'].shape



In [8]:
# # 定义更深的神经网络模型
# import torch
# import torch.nn as nn
# import torch.optim as optim
# import numpy as np
# from torch.utils.data import DataLoader
# import matplotlib.pyplot as plt
# from IPython.display import clear_output

# import src.Config as cf
# import trajectory_dataset as trajectory_dataset
# import uav_model as uav_model
# from src.kan.LBFGS import *

# from datetime import datetime
# import os

# gpu_cuda:bool = torch.cuda.is_available()
# print(f'Cuda with GPU support:{gpu_cuda}')


# # 创建训练和测试数据集
# train_dataset = trajectory_dataset.TrajectoryDataset(train_features_stage1, train_phis_labels_stage1)
# test_long_dataset = trajectory_dataset.TrajectoryDataset(test_features_stage1, test_phis_labels_stage1)
# # test_short_dataset = TrajectoryDataset.TrajectoryDataset(test_short_features, test_short_coor_labels)

# # 创建 DataLoader
# train_loader = DataLoader(train_dataset, batch_size=cf.train_batch_size, shuffle=True)

# # TODO: fix the batch size
# test_long_loader = DataLoader(test_long_dataset, batch_size=len(parted_lines_a), shuffle=False)
# # test_short_loader = DataLoader(test_short_dataset, batch_size=cf.test_set_short_num, shuffle=False)

# # 使用GPU加速
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# # 定义模型
# using_model = uav_model.UavModel()
# model = using_model.to(device)

# # 定义保存模型的路径，并添加时间戳
# timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")  # 格式化时间戳
# best_model_path = f"./models/{timestamp}"
# os.makedirs(best_model_path, exist_ok=True)

# # 加载现有模型的逻辑
# pretrained_model_path = "./keymodel/model.pth"  # 指定预训练模型路径
# if os.path.exists(pretrained_model_path):
#     print(f"Loading existing model from: {pretrained_model_path}")
#     model.load_state_dict(torch.load(pretrained_model_path, map_location=device))
# else:
#     print("No existing model found. Starting training from scratch.")

# # 打印模型参数信息
# for param in model.parameters():
#     print(type(param), param.size())

# # 损失函数和优化器
# if cf.optimizer == "Adam":
#     optimizer = optim.Adam(model.parameters(), lr=cf.learning_rate)
# elif cf.optimizer == "LBFGS":
#     optimizer = LBFGS(
#         model.parameters(),
#         lr=cf.learning_rate,
#         history_size=10,
#         line_search_fn="strong_wolfe",
#         tolerance_grad=1e-32,
#         tolerance_change=1e-32,
#         tolerance_ys=1e-32,
#     )
# criterion = nn.MSELoss()

# # 训练逻辑保持不变
# loss_values = []  # 存储损失值以供绘图
# global total_loss

# def closure():
#     global total_loss
#     optimizer.zero_grad()
#     outputs = model(features)
#     loss = criterion(outputs, labels)
#     loss.backward()
#     optimizer.step()
#     total_loss += loss.item()
#     return loss

# best_loss = float("inf")  # 初始化最小loss为正无穷

# for epoch in range(cf.epoch):
#     model.train()
#     total_loss = 0.0
#     for features, labels in train_loader:
#         features, labels = features.to(device), labels.to(device)
#         if cf.optimizer == 'LBFGS':
#             optimizer.step(closure)
#         else:
#             optimizer.zero_grad()
#             outputs = model(features)
#             loss = criterion(outputs, labels)
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item()
#     train_avg_loss = total_loss / len(train_loader)
#     loss_values.append(train_avg_loss)

#     # 动态绘图
#     clear_output(wait=True)
#     plt.figure(figsize=(12, 6))
#     plt.plot(loss_values, label="Loss")
#     plt.title("Loss Curve")
#     plt.xlabel("Epoch")
#     plt.ylabel("Loss")
#     plt.legend()
#     plt.text(epoch, loss.item(), f"Loss: {loss.item()}", ha="right")

#     train_result_name = training_results_folder + "/up-to-date-loss.png"
#     plt.savefig(train_result_name)
#     plt.show()

#     # 打印损失信息
#     print(f"Epoch [{epoch+1}/{cf.epoch}], Loss: {loss.item()}")

#     # 验证和保存最佳模型
#     model.eval()
#     total_test_long_loss = 0
#     total_test_short_loss = 0
#     predicted_labels = []
#     true_labels = []
#     with torch.no_grad():
#         for features, labels in test_long_loader:
#             features, labels = features.to(device), labels.to(device)
#             outputs = model(features)
#             test_long_loss = criterion(outputs, labels)
#             total_test_long_loss += test_long_loss.item()
#             predicted_labels.append(outputs.cpu().numpy())
#             true_labels.append(labels.cpu().numpy())
#         # for features, labels in test_short_loader:
#         #     features, labels = features.to(device), labels.to(device)
#         #     outputs = model(features)
#         #     test_short_loss = criterion(outputs, labels)
#         #     total_test_short_loss += test_short_loss.item()
#         #     predicted_labels.append(outputs.cpu().numpy())
#         #     true_labels.append(labels.cpu().numpy())

#     # 合并所有批次的预测结果和真实值
#     predicted_labels = np.concatenate(predicted_labels, axis=0)
#     true_labels = np.concatenate(true_labels, axis=0)

#     output_csv_file = f"{testing_results_folder_csv}/epoch-{epoch}-test-result.csv"
#     save_results_as_csv(true_labels, predicted_labels, output_csv_file)

#     long_loss = total_test_long_loss / len(test_long_loader)
#     # short_loss = total_test_short_loss / len(test_short_loader)

#     # 如果验证损失更小，则保存模型
#     if long_loss < best_loss:
#         best_loss = long_loss
#         best_model_filename = f"{best_model_path}/best_model_epoch_{epoch}.pth"
#         torch.save(model.state_dict(), best_model_filename)
#         print(f"New best model saved at epoch {epoch} with loss {best_loss:.6f}")

#     # if using distance, convert to xy
#     # true_xy = FeaturesAndLabelsGenerator.estimate_positions_optimized(true_labels, detecting_region_info)
#     # predicted_xy = FeaturesAndLabelsGenerator.estimate_positions_optimized(predicted_labels, detecting_region_info)

#     # if using coord, use directly
#     true_xy = true_labels
#     predicted_xy = predicted_labels

#     plot_result(
#         detecting_region_info=detecting_region_info,
#         loss_to_show=long_loss,
#         trues=true_xy,
#         predicteds=predicted_xy,
#         folder_name=testing_results_folder_plt,
#         plot_name=f"epoch-{epoch}-test-result.png"
#     )

#     print(f"TestLong Loss: {long_loss}")
#     # print(f"TestShort Loss: {short_loss}")


In [9]:
# 定义更深的神经网络模型
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
from IPython.display import clear_output

import src.Config as cf
import src.trajectory_dataset as trajectory_dataset
import src.uav_model as uav_model
from src.kan.LBFGS import *

from datetime import datetime
import os

gpu_cuda:bool = torch.cuda.is_available()
print(f'Cuda with GPU support:{gpu_cuda}')


# 创建训练和测试数据集
train_dataset = trajectory_dataset.TrajectoryDataset(train_features_stage1, train_phis_labels_stage1)
test_dataset = trajectory_dataset.TrajectoryDataset(test_features_stage1, test_phis_labels_stage1)
# test_short_dataset = TrajectoryDataset.TrajectoryDataset(test_short_features, test_short_coor_labels)

# 创建 DataLoader
train_loader = DataLoader(train_dataset, batch_size=cf.train_batch_size, shuffle=True)

# TODO: fix the batch size
test_loader = DataLoader(test_dataset, batch_size=config.train_batch_size, shuffle=False)
# test_short_loader = DataLoader(test_short_dataset, batch_size=cf.test_set_short_num, shuffle=False)

# 使用GPU加速
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 定义模型
using_model = uav_model.UavModel()
model = using_model.to(device)

# 定义保存模型的路径，并添加时间戳
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")  # 格式化时间戳
best_model_path = f"./models/{timestamp}"
os.makedirs(best_model_path, exist_ok=True)

# 加载现有模型的逻辑
pretrained_model_path = "./keymodel/model.pth"  # 指定预训练模型路径
if os.path.exists(pretrained_model_path):
    print(f"Loading existing model from: {pretrained_model_path}")
    model.load_state_dict(torch.load(pretrained_model_path, map_location=device))
else:
    print("No existing model found. Starting training from scratch.")

# 打印模型参数信息
for param in model.parameters():
    print(type(param), param.size())

# 损失函数和优化器
if cf.optimizer == "Adam":
    optimizer = optim.Adam(model.parameters(), lr=cf.learning_rate)
elif cf.optimizer == "LBFGS":
    optimizer = LBFGS(
        model.parameters(),
        lr=cf.learning_rate,
        history_size=10,
        line_search_fn="strong_wolfe",
        tolerance_grad=1e-32,
        tolerance_change=1e-32,
        tolerance_ys=1e-32,
    )
criterion = nn.MSELoss()

# 训练逻辑保持不变
loss_values = []  # 存储损失值以供绘图
global total_loss

best_loss = float("inf")  # 初始化最小loss为正无穷

for epoch in range(cf.epoch):
    model.train()
    total_loss = 0.0
    for features, labels in train_loader:
        features, labels = features.to(device), labels.to(device)
        if cf.optimizer == 'LBFGS':
            # define closure *per batch* so it captures the right features/labels
            def closure():
                optimizer.zero_grad()
                outputs = model(features)
                loss = criterion(outputs, labels)
                loss.backward()
                return loss

            # this will call your closure multiple times as needed
            loss = optimizer.step(closure)
            total_loss += loss.item()
        else:
            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
    train_avg_loss = total_loss / len(train_loader)
    loss_values.append(train_avg_loss)

    # 动态绘图
    clear_output(wait=True)
    plt.figure(figsize=(12, 6))
    plt.plot(loss_values, label="Loss")
    plt.title("Loss Curve")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.text(epoch, loss.item(), f"Loss: {loss.item()}", ha="right")

    train_result_name = training_results_folder + "/up-to-date-loss.png"
    plt.savefig(train_result_name)
    plt.show()

    # 打印损失信息
    print(f"Epoch [{epoch+1}/{cf.epoch}], Loss: {loss.item()}")

    # 验证和保存最佳模型
    model.eval()
    total_test_long_loss = 0
    total_test_short_loss = 0
    predicted_labels = []
    true_labels = []
    with torch.no_grad():
        for features, labels in test_loader:
            features, labels = features.to(device), labels.to(device)
            outputs = model(features)
            test_long_loss = criterion(outputs, labels)
            total_test_long_loss += test_long_loss.item()
            predicted_labels.append(outputs.cpu().numpy())
            true_labels.append(labels.cpu().numpy())
        # for features, labels in test_short_loader:
        #     features, labels = features.to(device), labels.to(device)
        #     outputs = model(features)
        #     test_short_loss = criterion(outputs, labels)
        #     total_test_short_loss += test_short_loss.item()
        #     predicted_labels.append(outputs.cpu().numpy())
        #     true_labels.append(labels.cpu().numpy())

    # 合并所有批次的预测结果和真实值
    predicted_labels = np.concatenate(predicted_labels, axis=0)
    true_labels = np.concatenate(true_labels, axis=0)

    output_csv_file = f"{testing_results_folder_csv}/epoch-{epoch}-test-result.csv"
    save_results_as_csv(true_labels, predicted_labels, output_csv_file)

    long_loss = total_test_long_loss / len(test_loader)
    # short_loss = total_test_short_loss / len(test_short_loader)

    # 如果验证损失更小，则保存模型
    if long_loss < best_loss:
        best_loss = long_loss
        print('best_loss',best_loss)
        best_model_filename = f"{best_model_path}/best_model_epoch_{epoch}.pth"
        torch.save(model.state_dict(), best_model_filename)
        print(f"New best model saved at epoch {epoch} with loss {best_loss:.6f}")



KeyboardInterrupt: 